name: Docker Publish

on:
  schedule:
    - cron: '23 12 * * *'
  push:
    branches: [ "main" ]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    uses: rwunderer/renovate/.github/workflows/reusable-docker-publish.yaml
    with:
      minimal-image: kubectl-minimal
      debug-image: kubectl-debug
      docker-description: Minimal Docker image with kubectl cli utility
    secrets: inherit
