name: Docker Publish

on:
  schedule:
    - cron: '23 12 * * *'
  push:
    branches: [ "main" ]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write

    uses: rwunderer/renovate/.github/workflows/reusable-docker-publish.yml@main
    with:
      minimal-image: kubectl-minimal
      debug-image: kubectl-debug
      docker-description: Minimal Docker image with kubectl cli utility
    secrets: inherit
