name: Docker Publish

on:
  schedule:
    - cron: '23 12 * * *'
  push:
    branches: [ "main" ]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write

    strategy:
      matrix:
        image:
        - minimal
        - debug

        include:
        - suffix: -minimal
          target: kubectl-minimal

        - suffix: -debug
          target: kubectl-debuG

    uses: rwunderer/renovate/.github/workflows/reusable-docker-publish.yml@main
    with:
      suffix: ${{ matrix.suffix }}
      target: ${{ matrix.target }}
      docker-description: Minimal Docker image with kubectl cli utility
    secrets: inherit
